package chap08;

public class ExceptionTest2 {

	public static void main(String[] args) {
		
		int [] arr = {1, 2, 3, 4, 5};
		
		System.out.println(arr[5]);
		
		/*
		try {
			System.out.println(arr[5]);
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("인덱스의 범위를 벗어난 접근 발생 !");
		}*/
		
		

	}

}
